// <auto-generated />
namespace DMS.API.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CityRequire : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CityRequire));
        
        string IMigrationMetadata.Id
        {
            get { return "201712271316006_CityRequire"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
